//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiemPortal6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTIEM_TeamRelation
    {
        public int TeamRelationId { get; set; }
        public int UserId { get; set; }
        public int TeamStatus { get; set; }
        public string WorkingArea { get; set; }
        public int TeamCategoryId { get; set; }
    
        public virtual PORTAL_User PORTAL_User { get; set; }
    }
}
