//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiemPortal6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstiemPortal5Entities : DbContext
    {
        public EstiemPortal5Entities()
            : base("name=EstiemPortal5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ESTIEM_Group> ESTIEM_Group { get; set; }
        public virtual DbSet<ESTIEM_LocalGroup> ESTIEM_LocalGroup { get; set; }
        public virtual DbSet<ESTIEM_RegionLocalGroup> ESTIEM_RegionLocalGroup { get; set; }
        public virtual DbSet<ESTIEM_RegionResponsible> ESTIEM_RegionResponsible { get; set; }
        public virtual DbSet<ESTIEM_TeamCategory> ESTIEM_TeamCategory { get; set; }
        public virtual DbSet<ESTIEM_TeamRelation> ESTIEM_TeamRelation { get; set; }
        public virtual DbSet<EVENTS_Events> EVENTS_Events { get; set; }
        public virtual DbSet<EVENTS_EventType> EVENTS_EventType { get; set; }
        public virtual DbSet<EVENTS_Participants> EVENTS_Participants { get; set; }
        public virtual DbSet<HTML_HtmlModule> HTML_HtmlModule { get; set; }
        public virtual DbSet<NEWS_Category> NEWS_Category { get; set; }
        public virtual DbSet<NEWS_News> NEWS_News { get; set; }
        public virtual DbSet<NEWS_Newsletter> NEWS_Newsletter { get; set; }
        public virtual DbSet<NEWS_NewsletterTemplate> NEWS_NewsletterTemplate { get; set; }
        public virtual DbSet<PORTAL_ESTIEMUser> PORTAL_ESTIEMUser { get; set; }
        public virtual DbSet<PORTAL_Role> PORTAL_Role { get; set; }
        public virtual DbSet<PORTAL_User> PORTAL_User { get; set; }
        public virtual DbSet<NEWS_NewsletterNews> NEWS_NewsletterNews { get; set; }
    }
}
