//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiemPortal6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTIEM_LocalGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTIEM_LocalGroup()
        {
            this.ESTIEM_Group = new HashSet<ESTIEM_Group>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public Nullable<int> MemberListId { get; set; }
        public Nullable<int> LRListId { get; set; }
        public string Address { get; set; }
        public string OfficialName { get; set; }
        public int Status { get; set; }
        public string UniversityName { get; set; }
        public int ActiveMemberCount { get; set; }
        public Nullable<System.DateTime> MembershipStart { get; set; }
        public Nullable<System.DateTime> MembershipEnd { get; set; }
        public string FreeText { get; set; }
        public Nullable<int> BoardResponsibleId { get; set; }
        public Nullable<int> LocalResponsibleId { get; set; }
        public Nullable<int> OldId { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public System.DateTime Created { get; set; }
        public string Coordinates { get; set; }
        public System.Guid Guid { get; set; }
        public string Alias { get; set; }
        public string GPSLocation { get; set; }
        public Nullable<int> MapCoordinateX { get; set; }
        public Nullable<int> MapCoordinateY { get; set; }
        public string LogoPath { get; set; }
        public string HomePage { get; set; }
        public string Email { get; set; }
        public string FreeTextField1 { get; set; }
        public string FreeTextField2 { get; set; }
        public string FreeTextField3 { get; set; }
        public string FreeTextField4 { get; set; }
        public string FreeTextField5 { get; set; }
        public string FreeTextField6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTIEM_Group> ESTIEM_Group { get; set; }
    }
}
