//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiemPortal6
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTS_Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTS_Events()
        {
            this.EVENTS_Participants = new HashSet<EVENTS_Participants>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HistoryId { get; set; }
        public int EventType { get; set; }
        public Nullable<int> RegistrationMode { get; set; }
        public Nullable<int> ConfirmationType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Place { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> ApplicationStartDate { get; set; }
        public Nullable<System.DateTime> ApplicationEndDate { get; set; }
        public Nullable<System.DateTime> RetireDeadline { get; set; }
        public Nullable<int> Maxparticipants { get; set; }
        public Nullable<int> MaxParticipantsPerLG { get; set; }
        public Nullable<int> ParticipationFee { get; set; }
        public string HomePage { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Youtube { get; set; }
        public Nullable<int> ParticipantsListGroupId { get; set; }
        public Nullable<int> WaitingListGroupId { get; set; }
        public string EmailListAlias { get; set; }
        public string XmlQuestions { get; set; }
        public Nullable<int> AdminUserId { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
        public Nullable<short> PartyLevel { get; set; }
        public Nullable<short> SelfDevLevel { get; set; }
        public Nullable<short> EDevLevel { get; set; }
        public Nullable<short> AContentLevel { get; set; }
        public Nullable<short> BContactLevel { get; set; }
        public Nullable<short> CultureLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTS_Participants> EVENTS_Participants { get; set; }
    }
}
