//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiemPortal6
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTS_Participants
    {
        public int EventID { get; set; }
        public int UserId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int RegistrationStatus { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CmStatus { get; set; }
        public string MotivationText { get; set; }
        public Nullable<bool> Vegetarian { get; set; }
        public Nullable<bool> NoPork { get; set; }
        public Nullable<bool> VisaRequired { get; set; }
        public string Visa_Firstname { get; set; }
        public string Visa_Surname { get; set; }
        public string Visa_Birthplace { get; set; }
        public Nullable<System.DateTime> Visa_Birthdate { get; set; }
        public string Visa_Nationality { get; set; }
        public string Visa_PassportNumber { get; set; }
        public Nullable<System.DateTime> Visa_PassportExpiryDate { get; set; }
        public Nullable<System.DateTime> Visa_PassportIssuedDate { get; set; }
        public string Visa_PassportIssuedBy { get; set; }
        public string Visa_Address { get; set; }
        public Nullable<System.DateTime> Travel_ArrivalDate { get; set; }
        public Nullable<System.DateTime> Travel_DepartureDate { get; set; }
        public string XmlAnswers { get; set; }
    
        public virtual EVENTS_Events EVENTS_Events { get; set; }
    }
}
