//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiemPortal6
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_NewsletterTemplate
    {
        public int Id { get; set; }
        public string Templatetitle { get; set; }
        public string HeaderHTML { get; set; }
        public string ContentHTML { get; set; }
        public string FooterHTML { get; set; }
        public string HeaderHTMLmail { get; set; }
        public string ContentHTMLmail { get; set; }
        public string FooterHTMLmail { get; set; }
        public bool isDefault { get; set; }
    }
}
