//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiemPortal6
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTAL_ESTIEMUser
    {
        public int UserId { get; set; }
        public string FirstNameEnglish { get; set; }
        public string LastNameEnglish { get; set; }
        public int Status { get; set; }
        public int AlumniStatus { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> IsOnMemberList { get; set; }
        public bool IsOnLocalGroupList { get; set; }
        public string MobilePhone { get; set; }
        public string Homepage { get; set; }
        public string Interests { get; set; }
        public string CouncilMeetings { get; set; }
        public string EstiemActivities { get; set; }
        public string OnlineIds { get; set; }
        public bool IsVegetarian { get; set; }
        public bool NoPork { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> StudiesStart { get; set; }
        public Nullable<System.DateTime> StudiesEnd { get; set; }
        public string HomeAddress { get; set; }
        public string OtherAddress { get; set; }
        public string BusinessAddress { get; set; }
        public string BirthName { get; set; }
        public byte[] Image { get; set; }
        public byte[] Thumbnail { get; set; }
        public Nullable<int> LocalGroupId { get; set; }
        public Nullable<int> ExchangeLocalGroupId { get; set; }
        public Nullable<int> OldId { get; set; }
        public System.Guid Guid { get; set; }
        public int MailStatus { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string SkypeName { get; set; }
        public string EstiemPositions { get; set; }
        public string StudyInfo { get; set; }
        public string Hometown { get; set; }
        public string DietInfo { get; set; }
        public string Visa_Firstname { get; set; }
        public string Visa_Surname { get; set; }
        public string Visa_Nationality { get; set; }
        public string Visa_PassportNumber { get; set; }
        public Nullable<System.DateTime> Visa_PassportExpiryDate { get; set; }
        public Nullable<System.DateTime> Visa_PassportIssuedDate { get; set; }
        public string Visa_PassportIssuedBy { get; set; }
        public Nullable<int> Visa_Address { get; set; }
        public string Visa_Birthplace { get; set; }
        public string EstiemComments { get; set; }
    }
}
