//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiemPortal6
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTAL_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PORTAL_Role()
        {
            this.PORTAL_User = new HashSet<PORTAL_User>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Alias { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
    
        public virtual ESTIEM_Group ESTIEM_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORTAL_User> PORTAL_User { get; set; }
    }
}
